### ISSUE TITLE
train issues

### ISSUE THREAD

**Issue by han666888999** [hualin95/Deeplab-v3plus#18]
When I run the train_voc.py,it run this issue.I don't know how to solve it 

Traceback (most recent call last):
  File "train_voc.py", line 453, in <module>
    agent.main()
  File "train_voc.py", line 120, in main
    self.train()
  File "train_voc.py", line 129, in train
    self.train_one_epoch()
  File "train_voc.py", line 167, in train_one_epoch
    for x, y, _ in tqdm_epoch:
  File "/home/mjiang/.local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 937, in __iter__
    for obj in iterable:
  File "/u/local/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 278, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/u/local/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 709, in __init__
    self._try_put_index()
  File "/u/local/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 826, in _try_put_index
    index = self._next_index()
  File "/u/local/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 318, in _next_index
    return next(self.sampler_iter)  # may raise StopIteration
  File "/u/local/anaconda3/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 199, in __iter__
    for idx in self.sampler:
TypeError: 'list_iterator' object is not callable

thanks~

**Comment by fanjing136** [comment]
您好！
       我在训练过程中出现一个很奇怪的问题，我训练了一个晚上了，可还是无法训练完成。一直处于epoch-2中训练。
![image](https://user-images.githubusercontent.com/45896090/102583799-466a0e00-4140-11eb-909b-6411ba2c529a.png)

**Comment by CharlesPikachu** [comment]
hello, how about trying this repo:https://github.com/SegmentationBLWX/sssegmentation
